services:
  - type: web
    name: flask-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 10000  # Render assigns a port automatically, so this is just a placeholder